#!/bin/bash

# Defining and validating arguments
if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <namespace> <resource_type> <command>"
    echo "Example: $0 kube-system pods get"
    exit 1
fi

NAMESPACE=$1
RESOURCE_TYPE=$2
COMMAND=$3

# Displaying the table header
echo "Resource, Namespace, Name, CPU, Memory"

# Running the kubectl command and processing the results
kubectl $COMMAND $RESOURCE_TYPE -n $NAMESPACE | tail -n +2 | awk -v resType="$RESOURCE_TYPE" -v ns="$NAMESPACE" '{print resType", " ns", "$1", "$2", "$3}'
